### ISSUE TITLE
Divide by zero whenever y-coordinates of 2 point particles are identical

### ISSUE THREAD

**Issue by zhenyudg** [Rbot427/electric-fields#5]
Divide by zero whenever y-coordinates of 2 point particles are identical

**Comment by Rbot427** [comment]
To clarify, this issue only occurs when field lines begin to implode on negative charges.  Thus, this issue is only a side-effect of #2

**Comment by Rbot427** [comment]
I added a collision checking function that should hopefully fix this issue.  Please reopen this issue if the bug persists.
